### ISSUE TITLE
[Bugfix] remove translateY from icon default styling

### ISSUE THREAD

**Issue by LJKaski** [vrk-kpa/suomifi-ui-components#148]
Causes problems with some use cases and the value should probably be adjusted elsewhere instead.

When fixed remove manual adjustment from design-system front page (ContentBoxes).

**Comment by J-Kallunki** [comment]
Check that those components where it is used now will get it in their styles (`yarn test` should warn about snapshots if not right).

After PR is merged ask for suomifi-ui-components new version release to get it first updated in the suomifi-design-system task.
