### ISSUE TITLE
Icons have issues in strict Content-Security-Policy environment

### ISSUE THREAD

**Issue by jaaqo** [vrk-kpa/suomifi-ui-components#156]
In order to work-around the style attribute issue explained in https://github.com/vrk-kpa/suomifi-icons/issues/15 I need to provide `className` for customization and set `color` attribute to either `null` or `{}` otherwise leaving it `undefined` it ends up with the default color set in https://github.com/vrk-kpa/suomifi-ui-components/blob/develop/src/core/Icon/Icon.tsx#L85

I think having to do:
```
<Icon color={{}} className="info" icon="infoFilled" mousePointer />
```
or
```
<Icon color={null} className="info" icon="infoFilled" mousePointer />
```

is not intended and should probably be addressed in https://github.com/vrk-kpa/suomifi-icons/issues/15

**Comment by J-Kallunki** [comment]
Needs release of `suomifi-icons` and updated that to suomifi-ui-components.

**Comment by J-Kallunki** [comment]
https://github.com/vrk-kpa/suomifi-icons/issues/17
