### ISSUE TITLE
Dropdown has wrong background color

### ISSUE THREAD

**Issue by jporola** [vrk-kpa/suomifi-ui-components#178]
Has been correct (white) before but now (version 0.2.5) color is wrong (gray). See attached screenshot.

![image](https://user-images.githubusercontent.com/16972843/65877638-d46ba480-e394-11e9-9b7e-d3e958ec90aa.png)

**Comment by J-Kallunki** [comment]
This will be not done before the `suomifi-design-tokens` is implemented.

**Comment by ketsappi** [comment]
> This will be not done before the `suomifi-design-tokens` is implemented.

This seems to be done now with the PR #186, so it doesn't block this issue anymore.
