### ISSUE TITLE
Misleading information architecture

### ISSUE THREAD

**Issue by thevangelist** [vrk-kpa/suomifi-ui-components#180]
Upon arriving to page: https://designsystem.suomi.fi/fi/

I find out that the most of the components compared to the same ones developed in react-styleguidist are missing. 

There's apparently a link on the footer, but I don't think anyone will find that.

I suggest changing `Tutustu käyttöliittymäkomponentteihin` link to point towards same one as the footer one.

Additionally, I think the roles between the the style guide and the design system (page) are misleading. 

"The styleguide can have all the details about the components, and the site can be a more easily approachable presentation of the design system as a whole. Wouldn't really make sense to clutter that with all of the available props of each component etc. "... This should be clarified on the intro page (https://designsystem.suomi.fi/fi/) in detail, and both links provided as essential resources for developers.

For example as two elements side by side that are clickable noticeably.

Currently as an external visitor to page it seems that there is not much progress (whereas the progress is hidden in github, that is found only on footer)

**Comment by J-Kallunki** [comment]
Wrong repository. I think you are referring to https://github.com/vrk-kpa/suomifi-design-system

I would contact `suomidigi-kehittajat`-slack or other contacts found from https://designsystem.suomi.fi/
