### ISSUE TITLE
Allow variable based theming

### ISSUE THREAD

**Issue by thevangelist** [vrk-kpa/suomifi-ui-components#181]
In order to make the design system easily usable in various types of projects, the system should allow changing of variables such as typography, borders, margins, colors, border-radius, etc. 

See for example: https://www.styled-components.com/docs/advanced

This would make the style system more usable in various applications. We could start with basic parameters such as "main colour".. Or limit the options to not very extensible, but still providing an obvious visual change for different systems that might use the system.

Can you make this happen?

**Comment by hoppula** [comment]
This is related to #79

**Comment by J-Kallunki** [comment]
This is being implemented. At currently every component allows theme.

But now that tokens are refactored and released in own [package (https://github.com/vrk-kpa/suomifi-design-tokens)](https://github.com/vrk-kpa/suomifi-design-tokens), implementing that to `suomifi-ui-components` needs a bit refactoring that is almost done. After that every component allows you to give tokens-prop as same object or parts of it as `suomifi-ui-tokens´ provides.

**Comment by J-Kallunki** [comment]
Actually after that either internal Theme-object or `suomifi-design-tokens` can be used
