### ISSUE TITLE
[Feat]: Codecov.io

### ISSUE THREAD

**Issue by J-Kallunki** [vrk-kpa/suomifi-ui-components#2]
Design usage for Codecov.io
Currently not allowing free open source with organizations:
https://docs.codecov.io/docs/frequently-asked-questions-1#section-is-there-a-discount-for-non-profit-or-education-organizations-

```json
"report-coverage": "cat ./coverage/lcov.info | codecov",
```

**Comment by J-Kallunki** [comment]
`.travis.yml:`
```yaml
after_success:
  - yarn report-coverage
```

**Comment by aappoalander** [comment]
Not relevant any more.
