### ISSUE TITLE
Create TestUtil for looping repeating components in tests

### ISSUE THREAD

**Issue by J-Kallunki** [vrk-kpa/suomifi-ui-components#204]
## The Problem

Testing components are made by making manual implementations of components. We don't have `suomifi-ui-component` app that would integration test all components with code changes made dev environment.

## Proposed Solution

Create util-component for generating easier test variations of components.

```
<TestUtil
  component={SuomifiComponent}
  props={variant: ['default', 'secondary', 'tertiary'], disabled: [true, false]}>
  <SuomifiComponent.item>This has no props need to be changed</SuomifiComponent>
  <TestUtil
    component={<SuomifiComponent variant="itemSecondary"/>}
    props={defaultOpen: [true, false], 'aria-label': [undefined, 'Test label']}>
  </TestUtil>
</TestUtil>
```

**Comment by aappoalander** [comment]
Closed due to difficulty of generalisation, different use cases that already exists do not benefit much from a util like this.
