### ISSUE TITLE
Find a cleaner syntax for typescript generics functions

### ISSUE THREAD

**Issue by J-Kallunki** [vrk-kpa/suomifi-ui-components#210]
## The Problem

This typing is always a pleasure to read! I would consider breaking it down for the sake of readability. Not as part of this PR though.

_Originally posted by @aappoalander in https://github.com/vrk-kpa/suomifi-ui-components/pull/207_

**Comment by aappoalander** [comment]
Will be dealt with in another way. Refactoring some unnecessary / unused abstractions away should get rid of the issue.
