### ISSUE TITLE
[Feature] Badges / shields to show useful & interesting info at glance

### ISSUE THREAD

**Issue by ketsappi** [vrk-kpa/suomifi-ui-components#214]
## The Problem

Currently the repo's README doesn't show the current version of the package or any other info that might be useful.

## Proposed Solution

In addition to showing version information, some other useful & interesting info could be shown in the README.

- **version**
  - ![npm](https://img.shields.io/npm/v/suomifi-ui-components)
- build status
  - ![CircleCI](https://img.shields.io/circleci/build/github/vrk-kpa/suomifi-ui-components)
- license
  - ![NPM](https://img.shields.io/npm/l/suomifi-ui-components)
- downloads?
  - ![npm](https://img.shields.io/npm/dm/suomifi-ui-components)
- Accessibility
  - ![WCAG](https://img.shields.io/badge/WCAG%202.1-AA-green)  

## Additional Info

If you are not sure what the badges / shields are, you can take a look here:
https://shields.io

**Comment by LJKaski** [comment]
This was fixed in #455.
