### ISSUE TITLE
TokensProvider (was ThemeProvider)

### ISSUE THREAD

**Issue by J-Kallunki** [vrk-kpa/suomifi-ui-components#225]
## The Problem

Custom tokens need to be given to every component separately.

## Proposed Solution

Component API has prop `tokens` as `PartialTokens`. Implement wrapper `SuomifiTokensProvider` with React context API - like Styled Components ThemeProvider.

## Alternative Solutions

`SuomifiThemeProvider` containing also internal theme customizations? Might be too complicated to get working as theme is based on tokens and what tokens are passed to define what theme etc.

## Additional Info

Implement themeProvider #79
https://www.styled-components.com/docs/advanced

**Comment by aappoalander** [comment]
Resolved by #491
