### ISSUE TITLE
Implement inputContainerProps as separate component

### ISSUE THREAD

**Issue by J-Kallunki** [vrk-kpa/suomifi-ui-components#233]
## The Problem

`TextInput` uses `inputContainerProps` that should be separate customizable children component to TextInput.

## Proposed Solution

Create:
`<TextInput.inputContainer />`
that implements what inputContainerProps is now doing.

**Comment by J-Kallunki** [comment]
Make sure that `SearchInput` has the same implementation.

**Comment by aappoalander** [comment]
If composition approach will be chosen, then more likely solution would be to have every part of the input as a separate components. E.g. `<TextInput> <Label>Label text</Label><InputElement style={style} /> <StatusText>Status</Status Text></TextInput>`
