### ISSUE TITLE
Opening the Menu will give error of missing prop 'to'

### ISSUE THREAD

**Issue by ketsappi** [vrk-kpa/suomifi-ui-components#237]
## Expected Behavior
Should not get any errors/warning when just opening the language menu.

## Possible Solution

The `@reach/menu-button`'s `MenuLink` seems to require the `to`-prop and giving it in 
`suomifi-ui-components/src/core/Menu/MenuLinkLanguage.tsx` will get rid of the error.

Maybe it should deconstruct `href` from props and pass the value to `to`-prop here?
https://github.com/vrk-kpa/suomifi-ui-components/blob/c466ca7b4c50e3317ac7e0c0d2acdfa2acb72668/src/core/Menu/MenuLinkLanguage.tsx#L14-L25

Also to be checked if the case can also be found in other places.

## Actual Behavior and Screenshots
Open the menu:
![image](https://user-images.githubusercontent.com/53757053/68481299-7f4a6a80-023f-11ea-9e28-ec4a88ec6edf.png)

## Steps to Reproduce the Problem

1. Run with 'yarn start'

2. Open the Patterns/Menu

3. Click the Menu to open it and receive the error in the console

## Specifications

- Version: **0.2.6**

**Comment by LJKaski** [comment]
Issue no longer seems to exist after recent updates to languagemenu
