### ISSUE TITLE
Add lang-attribute to styleguidist (update version)

### ISSUE THREAD

**Issue by J-Kallunki** [vrk-kpa/suomifi-ui-components#254]
## Expected Behavior or Possible Solution

Styleguidist to have `lang="en"` at `<html>`

Need to upgrade  React-styleguidist to >=  10.0.0

## Actual Behavior and Screenshots

```
<!DOCTYPE html>
  <html>
  <head>
```

## Specifications

- Version: 0.3.0

**Comment by aappoalander** [comment]
This has been done some time ago.
