### ISSUE TITLE
TextVariant for Text-component

### ISSUE THREAD

**Issue by ketsappi** [vrk-kpa/suomifi-ui-components#270]
## The Problem

Not being consistent in codebase.

https://github.com/vrk-kpa/suomifi-ui-components/blob/ed1e6a9863443dff08e3815d687d613523380916/src/core/Text/Text.tsx#L24

Following components have their variants in similar case:

- Breadcrumb
- Button
- Link
- Panel
- TextInput

## Proposed Solution

`type TextVariant = 'body' | 'lead' | 'bold';`

`variant?: TextVariant;`

**Comment by saksham93** [comment]
@ketsappi - Can you please review PR #273 for this issue? Thank you.

**Comment by ketsappi** [comment]
Thanks for your contribution @saksham93! 
We will go through the PR at a later time. There are some higher priority tasks at the hand currently that we are focusing now.

**Comment by ketsappi** [comment]
Issue will be closed as it is no longer valid. 

See the comment from the related PR:
https://github.com/vrk-kpa/suomifi-ui-components/pull/273#issuecomment-587523785
