### ISSUE TITLE
Create utils for common classnames usage

### ISSUE THREAD

**Issue by J-Kallunki** [vrk-kpa/suomifi-ui-components#33]
Create utils like:
- `className={classnames(className, baseClassName)}`

**Comment by J-Kallunki** [comment]
Should it be just function that will be given className, baseClassName and then array of objects with postfix-keys and their conditions?

Example what repeating code to get:
```
className={classnames(className, {
        [`${baseClassName}--padding-${padding}`]: !!padding,
        [`${baseClassName}--margin-${margin}`]: !!margin,
        [`${baseClassName}--${passProps.variant}`]: !!passProps.variant,
      })}
```

**Comment by aappoalander** [comment]
Already implemented to sufficient level.
