### ISSUE TITLE
Make consistency for Menu props/classNames

### ISSUE THREAD

**Issue by J-Kallunki** [vrk-kpa/suomifi-ui-components#42]
Now the Menu component's Button will get all other properties but not className that is given to the Menu-container (span) and Button's className is menuButtonClassName. Refactor so that it is more simple and clear not splitting the properties and passing cross.

**Comment by J-Kallunki** [comment]
I'll figure out this later what it is

**Comment by aappoalander** [comment]
Fixed as many component structures have already being aligned and prop handling made more uniform.
