### ISSUE TITLE
"ReferenceError: Can't find variable: process" when importing & using component

### ISSUE THREAD

**Issue by ovaris** [vrk-kpa/suomifi-ui-components#578]
## Actual Behavior and Screenshots

Hi!, I wanted to just quickly test suomifi-ui-components with fresh CRA (create-react-app), but as soon as I try to import any component from lib, browser throws this error:
 ReferenceError: Can't find variable: process

So something's not right in webpack's build configs etc:
<img width="301" alt="image" src="https://user-images.githubusercontent.com/2553533/157251029-6f82aa46-9d1d-44d3-bce3-8417c1e89072.png">

## Steps to Reproduce the Problem

1. `npx create-react-app test_app --template typescript `
2. `cd test_app`
3. `yarn add styled-components `
4. ` yarn add suomifi-ui-components `
5.  Add suomifi css import to index.tsx `import 'suomifi-ui-components/dist/main.css';`6. 
6.  add font css @import to index.css file
7. Import any suomifi component to App.tsx and include in rendered component, for example `<Alert closeText='close me'>HOOORAy</Alert>`
## Specifications

- Version: latest

### Environment: (if related to the issue)

- CRA latest
- MacOS
- Node 17.4

**Comment by ovaris** [comment]
Pinpointed error to logger ( src/utils/log/logger.ts) which referencing to process, or it was before recent change, which is not I guess yet published into NPM

**Comment by ovaris** [comment]
To fix this issue I added following to index.html 🙂 
```
<script>
      var process = {};
    </script>
```

**Comment by ketsappi** [comment]
Thanks for the report!

This issue with the logger should be fixed in the following PR: #563
Hopefully we can get the fix in the next stable release, `7.0.0`

**Comment by ketsappi** [comment]
This fix is now currently available in beta:  [`7.0.0-beta.0`](https://github.com/vrk-kpa/suomifi-ui-components/releases/tag/v7.0.0-beta.0)

**Comment by riitasointi** [comment]
As stated in the previous comment, this fix is now available in version `7.0.0` which is (at the time of writing this comment) the latest stable release of this library.
