### ISSUE TITLE
Monorepo or tree shaking

### ISSUE THREAD

**Issue by J-Kallunki** [vrk-kpa/suomifi-ui-components#59]
Design a need fo a monorepo-system to have separate component packages to be used optimally.

Is Ant-Design alike tree shaking support enough?

**Comment by aappoalander** [comment]
Tree shaking is already supported via es-module build. Monorepo structure with multiple packages was researched, but found unsuitable due to difficulty of maintaining different versions of shared code like themes and tooling.
