### ISSUE TITLE
Improve example code for Breadcrumb

### ISSUE THREAD

**Issue by danielck** [vrk-kpa/suomifi-ui-components#728]
## The Problem

The example aria-label for the Breadcrumb component is `breadcrumb`, which is not necessarily understandable for non-designers or non-developers. This can give the wrong signal to consumers of the component.

## Proposed Solution

Use a more descriptive text such as "You are here" or "Your current location".

**Comment by jenkrisu** [comment]
Good point! I added a task to improve these examples for the Breadcrumb component.
