### ISSUE TITLE
Some disabled elements do not appear visually disabled in Windows High Contrast mode

### ISSUE THREAD

**Issue by danielck** [vrk-kpa/suomifi-ui-components#744]
## Expected Behavior or Possible Solution

Different component states should be visually distinct in Windows High Contrast Mode or in newer Windows versions, Windows Contrast Themes.

## Actual Behavior and Screenshots

Elements which are aria-disabled do not look different from other elements, e.g. disabled dates in the DateInput date pickers.

<img width="743" alt="Screenshot 2023-06-15 at 11 46 33" src="https://github.com/vrk-kpa/suomifi-ui-components/assets/657814/165f178d-4787-4f2c-9dc4-460a34ab6014">
<img width="435" alt="Screenshot 2023-06-15 at 12 06 16" src="https://github.com/vrk-kpa/suomifi-ui-components/assets/657814/3252b0ed-97fa-434a-b30a-bd49de8a3989">

## Steps to Reproduce the Problem

1. Activate Contrast Themes in Windows 11 or test with forced-colors emulation in Chrome
2. View "DateInput with dates disabled" and open the date picker.
3. The weekends should look disabled, but they don't.

## Possible solution

One solution would be to use native `disabled`. Or define the style separately for Windows High Contrast.

**Comment by danielck** [comment]
A quick fix to this would be to make sure the system color `GrayText` is used for aria-disabled elements in High Contrast Themes.

```
@media screen and (forced-colors: active) {
   [aria-disabled="true"] { color: GrayText; }
}
```

**Comment by jenkrisu** [comment]
Good catch! We added a ticket about this.

**Comment by danielck** [comment]
Another case where this is evident is in disabled chips.

![Screenshot 2023-08-18 at 8 40 26](https://github.com/vrk-kpa/suomifi-ui-components/assets/657814/65282241-4600-4175-8051-74a4d463ceab)
