### ISSUE TITLE
Button for toggling all expanders in an ExpanderGroup changes both text and state

### ISSUE THREAD

**Issue by danielck** [vrk-kpa/suomifi-ui-components#764]
## Expected Behavior

A control where the action changes after activation should not simultaneously change its programmatic state. On the Open all / close all button, the text already communicates what will happen when activating the button. Also, there is only a loose connection between this toggle and the individual expanders, because it is possible for some to be closed and some open, so this programmatic state is not necessarily accurate.

## Actual Behavior

Initially, the button text is "Open all", and the state is "collapsed". After activation, the text is "Close all", and the state is "expanded". If one of the expanders is collapsed, the "Close all" button changes to "Open all" and the expanded state is also changed back to "collapsed", even though this is not quite accurate.

## Suggested fix

Remove the aria-expanded attribute entirely from the Open all / Close button.

**Comment by LJKaski** [comment]
This was resolved in the latest release.
